fix: Add meta tags and preview image for SEO optimization
ykdojo/defaang pull request #241
Opened 2022-10-03 08:06 UTC by devXprite

### ➕ Changes Introduced
Add meta tags for SEO optimization & add [this](https://user-images.githubusercontent.com/1811651/190090988-bd062b3d-635b-4ce1-ac15-81d3c9edcb91.png) img from Readme as  preview image for Twitter & Open Graph.

### 📷 Screenshots
**Before:**
In this Screenshot meta tags have default comments.
![before](https://user-images.githubusercontent.com/80192140/193527599-3ca698ac-9f7b-42f5-b701-0ac5d9836121.png)

**After:**
![after](https://user-images.githubusercontent.com/80192140/193527679-2b892269-6339-430d-bb51-2964e398e003.png)

2022-10-03 17:45 UTC, ykdojo requested changes

2022-10-03 17:45 UTC, ykdojo commented on src/pages/index.tsx
> +        <title>Defaang</title>
revert back to the original title

2022-10-03 17:45 UTC, ykdojo commented on src/pages/index.tsx
> +        <meta
The metatags are in _document.tsx. Should it be fixed there instead?

2022-10-03 17:45 UTC, ykdojo commented on src/pages/index.tsx
> +        <meta name='title' content='Defaang' />
lowercase Defaang

2022-10-04 01:56 UTC, devXprite commented
@ykdojo I Did the suggested changes!!

2022-10-04 15:53 UTC, ykdojo approved these changes

2022-10-04 15:54 UTC, merged